import { Moment } from 'moment';
import { EventType } from './enums/event-type';
import { EventRegistration } from './event-registration';
import { EventCompetition } from './event-competition';
import { PaymentMethodCash } from './payment-method-cash';
import { PaymentMethodSepa } from './payment-method-sepa';

export type Event = {
  id: string | undefined;
  name: string;
  alias: string;
  dateFrom: Moment;
  dateTo: Moment;
  participationFee: number;
  registrationOpen: Moment;
  registrationDeadline: Moment;
  description: string;
  venueHouseNo: string;
  venueStreet: string;
  venueCity: string;
  venuePostCode: string;
  venueCountry: string;
  type: EventType;
  livestreamUrl: string;
  paymentMethodCash: PaymentMethodCash;
  paymentMethodSepa: PaymentMethodSepa;
  autoApproveRegistrations: boolean;
  eventRegistrations: EventRegistration[];
  eventCompetitions: EventCompetition[];
  published: boolean;
};
