import { EventType } from './enums/event-type';
import { EventRegistration } from './event-registration';
import { EventCompetition } from './event-competition';
import { PaymentMethodCash } from './payment-method-cash';
import { PaymentMethodSepa } from './payment-method-sepa';
import { Moment } from 'moment';

export type Event = {
  id?: string;
  name: string;
  alias: string;
  admin?: string;
  dateFrom: string;
  dateTo: string;
  registrationOpen: string;
  registrationDeadline: string;
  participationFee: number;
  description: string;
  venueHouseNo: string;
  venueStreet: string;
  venueCity: string;
  venuePostCode: string;
  venueCountry: string;
  type: EventType;
  livestreamUrl: string;
  paymentMethodCash: PaymentMethodCash;
  paymentMethodSepa: PaymentMethodSepa;
  autoApproveRegistrations: boolean;
  notifyOnRegistration: boolean;
  notifyOnComment: boolean;
  eventRegistrations: EventRegistration[];
  eventCompetitions: EventCompetition[];
  published: boolean;
};
