import { ShowExperience } from '../domain/enums/show-experience';
import { UserType } from '../domain/enums/user-type';
import { UserVerificationState } from '../domain/enums/user-verification-state';

export type User = {
  username: string;
  type: UserType;
  imageUrl?: string;
  firstName?: string;
  lastName?: string;
  nickName?: string;
  gender?: string;
  country?: string;
  age?: number;
  freestyleSince?: number;
  instagramHandle?: string;
  tikTokHandle?: string;
  youTubeHandle?: string;
  website?: string;
  verificationState?: UserVerificationState;
  birthday?: string;
  tShirtSize?: string;
  houseNumber?: string;
  street?: string;
  postCode?: string;
  city?: string;
  exposeLocation?: boolean;
  locLatitude?: number;
  locLongitude?: number;
  jobAcceptTerms?: boolean;
  jobOfferShows?: boolean;
  jobOfferWalkActs?: boolean;
  jobOfferWorkshops?: boolean;
  jobShowExperience?: ShowExperience;
  phoneCountryCode?: number;
  phoneNumber?: number;
  wffaId?: string;
};
