version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - env | grep -e AUTH_TRUST_HOST -e NEXTAUTH_SECRET -e NEXTAUTH_URL -e GOOGLE_MAPS_API_KEY >> .env.production
        - yarn run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - .next/cache/**/*
      - node_modules/**/*