name: ci

on:
  push:
    branches:
      - main
      - dev
      - dev-ui
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      TAGS: nilsfs7/fsmeet-frontend:dev
      AUTH_URL: https://dev.fsmeet.dffb.org
      BACKEND_URL: https://api.dev.fsmeet.dffb.org
    steps:
      - name: Set environment by branch
        id: build-args
        run: |
          echo "BUILD_TIME=$(date -u +'%Y-%m-%d %H:%M:%S')" >> "$GITHUB_ENV"
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
              echo "set values for production image"
              
              echo "TAGS=nilsfs7/fsmeet-frontend:latest,nilsfs7/fsmeet-frontend:prod" >> "$GITHUB_ENV"
              echo "AUTH_URL=https://fsmeet.com" >> "$GITHUB_ENV"
              echo "BACKEND_URL=https://api.fsmeet.dffb.org" >> "$GITHUB_ENV"
          fi
          if [[ $GITHUB_REF == 'refs/heads/dev-ui' ]]; then
              echo "set values for dev-ui image"
              
              echo "TAGS=luisnaldo7/fsmeet-frontend:dev-ui" >> "$GITHUB_ENV"
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        env:
          SHA: ${{ github.sha }}
          MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
        with:
          push: true
          file: ./Dockerfile
          tags: ${{ env.TAGS }}
          build-args: |
            AUTH_URL=${{ env.AUTH_URL }}
            BACKEND_URL=${{ env.BACKEND_URL }}
            BUILD_TIME=${{ env.BUILD_TIME }}
            COMMIT_SHA=${{ env.SHA }}
            GOOGLE_MAPS_API_KEY=${{ env.MAPS_API_KEY }}
