name: ci

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      TAGS: luisnaldo7/fsjudge-frontend:dev
      AUTH_URL: http://dffb.org:9211
      BACKEND_URL: http://dffb.org:9210
    steps:
      - name: Set environment for branch
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
              echo "TAGS=luisnaldo7/fsjudge-frontend:latest,luisnaldo7/fsjudge-frontend:prod" >> "$GITHUB_ENV"
              echo "AUTH_URL=http://dffb.org:9201" >> "$GITHUB_ENV"
              echo "BACKEND_URL=http://dffb.org:9200" >> "$GITHUB_ENV"
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        env:
          AUTH_URL: ${{ env.AUTH_URL }}
          BACKEND_URL: ${{ env.BACKEND_URL }}
          SHA: ${{ github.sha }}
        with:
          push: true
          file: ./Dockerfile
          tags: ${{ env.TAGS }}
          build-args: |
            COMMIT_SHA=${{ env.SHA }}
